apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: nks-aiautomatisering
  name: nks-slackbob
  namespace: nks-aiautomatisering
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  envFrom:
    - secret: slackbot
  image: "{{ image }}"
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: nks-kbs
      external:
        - host: slack.com
        - host: hooks.slack.com
        - host: api.slack.com
        - host: wss-primary.slack.com
  azure:
    application:
      tenant: nav.no # Gjør at man kan logge på med vanlig konto i dev-gcp
      enabled: true
