apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: nks-aiautomatisering
  name: nks-slackbob
  namespace: nks-aiautomatisering
spec:
  envFrom:
    - secret: slackbot
  image: "{{ image }}"
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: nks-kbs
      external:
        - host: hooks.slack.com
        - host: slack.com
        - ipv4: 18.134.215.41
        - ipv4: 18.159.197.225
        - ipv4: 18.168.172.238
        - ipv4: 18.169.120.191
        - ipv4: 18.169.61.189
        - ipv4: 3.68.124.168
        - ipv4: 3.68.124.95
        - ipv4: 3.68.170.153
        - ipv4: 3.68.175.98
        - ipv4: 52.29.238.212
  azure:
    application:
      tenant: nav.no # Gjør at man kan logge på med vanlig konto i dev-gcp
      enabled: true
